>library ("BarcodingR")
>install.packages("BarcodingR")
>install.packages("BarcodingR")
install.packages("SPlits")
library(SPlits)
library(paran)
install.packages("splits",repos="http://R-Forge.R-project.org")
library(splits)
library("paran")
install.packages("splits",repos="http://R-Forge.R-project.org")

